# Generated by Django 2.0.4 on 2018-04-28 13:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtsp_solver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSP_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nodes', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('first_node', models.IntegerField(null=True)),
                ('processing_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
