# Generated by Django 2.0.4 on 2018-05-03 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtsp_solver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSPLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nodes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=2), null=True, size=None)),
                ('first_node', models.IntegerField(null=True)),
                ('processing_time', models.IntegerField(null=True)),
                ('solution', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
