# Generated by Django 2.0.4 on 2018-05-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtsp_solver', '0002_auto_20180503_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsplog',
            name='steps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tsplog',
            name='tol',
            field=models.IntegerField(null=True),
        ),
    ]
