# Generated by Django 2.0.4 on 2018-04-28 14:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtsp_solver', '0002_auto_20180428_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsp_log',
            name='nodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=2), null=True, size=None),
        ),
    ]
