# Generated by Django 2.0.4 on 2018-04-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qtsp_solver', '0003_auto_20180428_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TSP_log',
            new_name='TSPLog',
        ),
    ]
