# Generated by Django 2.0.4 on 2018-06-24 10:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qtsp_solver', '0003_auto_20180503_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsplog',
            name='distribution',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
