# Generated by Django 2.0.4 on 2018-04-28 14:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtsp_solver', '0004_auto_20180428_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsplog',
            name='solution',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
    ]
